from typing import ClassVar


class Hazelconf:

    """

    Configuration class generated by Queenconf

    """

    def __init__(self):

        self.config = Config()


class Menu:
    def __init__(self):
        pass

    settingsIcon: ClassVar[str] = 'mechanics'
class Config:
    def __init__(self):
        pass

    rowsPerPage: ClassVar[int] = 4
    showBlackFridayBanner: ClassVar[bool] = False
    showExtraHeader: ClassVar[bool] = False
    menu: ClassVar[class] = Menu()

